---
version: '2.1'

services:
  rancid: &defaults
    image: rancid
    build:
      context: src/
    stdin_open: true
    tty: true
    read_only: true
    cap_drop:
      - all
    pids_limit: 30
    cpu_shares: 1023
    mem_limit: 512M
    shm_size: 32M

  help:
    <<: *defaults
    entrypoint: rancid
    command: -h

  version:
    image: rancid
    entrypoint:
      - sh
    command:
      - -c
      - "apk policy rancid 2>/dev/null | tail -n +2 | head -1 | tr -d ' :'"
