version: '2.1'

services:
  rancid: &defaults
    image: rancid
    build:
      context: ./
      args:
        - VERSION
        - RELEASE
    stdin_open: true
    tty: true
    read_only: true

  help:
    <<: *defaults
    entrypoint: rancid
    command: -h

  version:
    <<: *defaults
    entrypoint: rancid
    command: -V
