version: '2.1'

services:
  rancid: &defaults
    image: rancid
    build:
      context: ./
    stdin_open: true
    tty: true
    read_only: true

  help:
    <<: *defaults
    entrypoint: rancid
    command: -h
